name = "play-jonny-casino-com-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=play-jonny-casino.com.de"
HMAC_KEY = "47de260ac4cf41858fbcb9155d4bb811502196a8c9990997568be1af33a9d52b"
COOKIE_NAME = "jmm"
PLAY_PATH = "play-now"
BUTTON_ID = "pd9b71296d07fe90d4583503f359d9486"
GATE_SALT = "034a73f98c903e5c"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "tze7"
CTA_SELECTOR = ".play-button"
